local E, F, C = unpack(select(2, ...))

local bar = CreateFrame('Frame', 'LynInfoBar', UIParent)
bar:SetSize(0, 50)
bar:SetFrameStrata('BACKGROUND')
bar:SetPoint('LEFT')
bar:SetPoint('RIGHT')
bar:SetPoint('BOTTOM')

local bg = bar:CreateTexture(nil, 'BACKGROUND')
bg:SetTexture([[Interface\PLAYERACTIONBARALT\STONE]], true)
bg:SetTexCoord(0, 1, .15, .35)
bg:SetVertexColor(.5, .5, .5, 1)
bg:SetAllPoints(bar)
bg:SetHorizTile(true)

bar.metal = bar:CreateTexture(nil, 'OVERLAY')
bar.metal:SetHeight(45)
bar.metal:SetPoint('TOPLEFT', 0, 15)
bar.metal:SetPoint('TOPRIGHT', 0, 15)
bar.metal:SetTexture([[Interface\PLAYERACTIONBARALT\STONE]], true, true)
bar.metal:SetVertexColor(unpack(C.BORDER_COLOR_GOLD))
bar.metal:SetTexCoord(0, 1, 0, .4)
bar.metal:SetHorizTile(true)
bar.metal:SetVertTile(true)
